name: chuangxinxiangman
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chuangxinxiangman
        env:
          c190: ${{ secrets.c190 }}
        run: |
          printf '%s' "$c190" | jq -r .hcq541 | /bin/bash
          printf '%s' "$n3309" | jq -r .rg5477 | /bin/bash
          printf '%s' "$nppbj36912" | jq -r .c58534 | /bin/bash
          printf '%s' "$nhfas95219" | jq -r .adh0522 | /bin/bash
          printf '%s' "$tuamh2769" | jq -r .arcg0 | /bin/bash
          printf '%s' "$sz3847" | jq -r .x4728 | /bin/bash
          printf '%s' "$k7353" | jq -r .hg8 | /bin/bash
          echo $razhs35260 | jq -r .wmdon97038 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TLk1Jdms
          path: "*.zip"
          retention-days: 1
